services:
  flaskapp:
    container_name: flaskapp
    build:
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8081:8081
    depends_on:
      - mongodb
  

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017