apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: MTIzNA==


# [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes())